### ISSUE TITLE
23.1.1 Händelse som ej är bunden till skola/kurs/klass försvinner när man krymper webbfönster

### ISSUE THREAD

**Issue by teknikMarit** [ADK-Lulu/LMS-Grupp-awesome#58]
Händelser i kalender som inte är bunden till skola/kurs/klass försvinner om man krymper fönstret så det byter till mobilläge och sen väntar 7 sekunder som lärare eller direkt som admin. De kommer tillbaka om man refreschar sidan.

/Denna bugg hittade jag och och Sören tillsammans när vi par-testade.

**Comment by StinaOdebo** [comment]
Lyckas inte återskapa problemet!

**Comment by ADK-Lulu** [comment]
Lyckas inte återskapa problemet.

**Comment by Soren-S** [comment]
Buggen är borta
